### ISSUE TITLE
return empty error?

### ISSUE THREAD

**Issue by Grummfy** [badrap/result#6]
Hello,
sometimes I jsut want to return an error but with no value, for the moment I do this :
```
return Result.err(new Error())
```
But I would prefer something like this
```
return Result.err()
```

**Comment by pawndev** [comment]
I just did a PR for that, waiting for reviewer right now. #7

**Comment by jviide** [comment]
I'm sorry for the huge delay for reviewing the pull request, I managed to miss the notification about it.

@pawndev's PR has now been merged, and I also added a test and docs for the new functionality. Updated the dependencies as well. The new version has now been published as v0.2.7 in [npm](https://www.npmjs.com/package/@badrap/result).

Thank you 🙂
